### ISSUE TITLE
Cannot activate plugin

### ISSUE THREAD

**Issue by matcss** [fossfreedom/coverart-search-providers#19]
Fedora
(Korora 21)
Gnome 3.14.2

As requested, Terminal output, though doubtlessly useless.

```
(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist


(rhythmbox:26536): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

```

**Comment by fossfreedom** [comment]
hmm - and you tried to enable coverart-browser - there should be extra stuff being displayed in the terminal when you enable the plugin.

Try start rhythmbox again - this time with the following command

    rhythmbox -D coverart

**Comment by matcss** [comment]
Well I did say I was a n00b! Nothing in Terminal when starting with that switch, but the following appears when I then try to activate plugin:

```
(rhythmbox:27322): libpeas-WARNING **: Could not find plugin 'coverart_search_providers' for plugin 'coverart_browser'
```

**Comment by fossfreedom** [comment]
that's better!

what is the contents of the following folder?

    cd ~/.local/share/rhythmbox/plugins
    ls

**Comment by matcss** [comment]
```
[13:24] mat@localhost ~ $ cd ~/.local/share/rhythmbox/plugins
[13:24] mat@localhost plugins $ ls
coverart-browser
[13:24] mat@localhost plugins $ 
```

**Comment by fossfreedom** [comment]
ok

  you havent yet installed the plugin coverart-search-providers

 - https://github.com/fossfreedom/coverart-search-providers
 use the section entitled "How to install - Rhythmbox 3.0 and later:"

**Comment by matcss** [comment]
I have installed it. Possibly incorrectly, but have definitely done so. That's why my earlier comment about paths - I suspect it's ending up in wrong place!

**Comment by fossfreedom** [comment]
step me through the exact instructions you have used.

are you using git clone straight into ~/.local/share/rhythmbox/plugins ?

**Comment by matcss** [comment]
I'm copying and pasting exactly as per instructions there:

```
rm -rf ~/.local/share/rhythmbox/plugins/coverart_search_providers
git clone https://github.com/fossfreedom/coverart-search-providers.git
cd coverart-search-providers
./install.sh
```

**Comment by fossfreedom** [comment]
Which folder are you in when you run those commands? 

     cd ~/Downloads

?

**Comment by matcss** [comment]
You're being very patient, thanks.

So, can now activate after running commands in /Downloads. Progress.

However, still not showing in RB.

Started from Terminal and get this on shutdown. Not sure if relevant.

```
Traceback (most recent call last):
  File "/home/mat/.local/share/rhythmbox/plugins/coverart-browser/coverart_browser.py", line 118, in do_deactivate
    self.source.delete_thyself()
AttributeError: 'CoverArtBrowserPlugin' object has no attribute 'source'

(rhythmbox:28290): Gtk-WARNING **: mnemonic "s" wasn't removed for widget (0x14a28d0)
```

**Comment by matcss** [comment]
Just FYI, the plugin shows an active 'Preferences' button, but nothing happens when clicking it.

**Comment by fossfreedom** [comment]
yep - you've got your old failed folder still in play.

please delete it.

rm -rf ~/.local/share/rhythmbox/plugins/coverart-browser

Then repeat the installation of coverart-browser plugin ... starting from ~/Downloads folder

**Comment by matcss** [comment]
Really trying your patience now. Ran all from /Downloads and now not showing in plugin list. Need to go out for a few hours, but this is clearly down to fundamental idiocy on my part, so will remove all and start from top again later.

**Comment by matcss** [comment]
And got there in the end. A little knowledge is truly a dangerous thing.

**Comment by fossfreedom** [comment]
you are most welcome :)
